
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE FOOD CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE IMAGE CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_NID CASCADE;
DROP SEQUENCE SEQ_RID CASCADE;
DROP SEQUENCE SEQ_FID CASCADE;
DROP SEQUENCE SEQ_BID CASCADE;
DROP SEQUENCE SEQ_IID CASCADE;


--------------------------------------------------
--------------     MEMBER 관련	------------------	
--------------------------------------------------


CREATE TABLE MEMBER (
	USER_ID	VARCHAR2(20) PRIMARY KEY,
	USER_PWD	VARCHAR2(30)	NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    PHONE	VARCHAR2(13)	NOT NULL,
	USER_EMAIL	VARCHAR2(50)	NOT NULL,
	GENDER	CHAR(1)		DEFAULT 'M',
    ADDRESS VARCHAR2(100)    NOT NULL,	
	BORN_DATE	DATE    NOT NULL,	
  	ENROLL_DATE DATE    DEFAULT SYSDATE,
  	STATUS VARCHAR2(1) DEFAULT 'Y'
					             
);

INSERT INTO MZ.MEMBER VALUES ('admin', '1234', '관리자',  '010-1111-2222', 'admin@naver.com', 'M', '서울시 분당구 정자동', to_date('90/02/06','RR/MM/DD'), SYSDATE, DEFAULT);
INSERT INTO MZ.MEMBER VALUES ('user01', 'pass01', '최기현', '010-1111-1111', 'user01@naver.com', 'M', '성남시 분당구 판교동', to_date('94/02/06','RR/MM/DD'), SYSDATE, DEFAULT);
INSERT INTO MZ.MEMBER VALUES ('user02', 'pass02', '이재환', '010-2222-5555', 'user02@naver.com', 'M', '인천시 부평구 부개동', to_date('92/02/06','RR/MM/DD') , SYSDATE, DEFAULT);
INSERT INTO MZ.MEMBER VALUES ('user03', 'pass03', '정다솜', '010-3333-4444', 'user03@naver.com', 'W', '광주시 서구 치평동', to_date('92/02/06','RR/MM/DD'), SYSDATE, DEFAULT);
INSERT INTO MZ.MEMBER VALUES ('user04', 'pass04', '최신영', '010-5555-4444', 'user04@naver.com', 'M', '서울시 양천구 목동', to_date('88/02/06','RR/MM/DD'), SYSDATE, DEFAULT);



--------------------------------------------------
--------------     NOTICE 관련	------------------	
--------------------------------------------------

CREATE TABLE NOTICE (
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(100) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
  NOTICE_WRITER VARCHAR2(30) NOT NULL,
  NOTICE_COUNT NUMBER DEFAULT 0,
  NOTICE_DATE DATE DEFAULT SYSDATE,
  STATUS CHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_NID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE
NOCACHE;

INSERT INTO NOTICE
VALUES (SEQ_NID.NEXTVAL, '첫번째 공지사항입니다.', '환영합니다.', 'admin', DEFAULT, SYSDATE, DEFAULT);




--------------------------------------------------
--------------     REPLY 관련	------------------	
--------------------------------------------------


CREATE TABLE REPLY (
	REPLY_NO	NUMBER PRIMARY KEY,
	REPLY_DATE DATE,
	REPLY_CONTENT	VARCHAR2(300)	NOT NULL,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
	BOARD_NO	NUMBER	NOT NULL,
	USER_ID	VARCHAR2(30)	NOT NULL,
	NOTICE_NO	NUMBER	NOT NULL,
    COFOREIGN KEY (RESTAURANT_NO) REFERENCES NOTICE(NOTICE_NO),            --외래키 추가
	FOREIGN KEY (USER_ID) REFERENCES MEMBER,          --외래키로 추가
	FOREIGN KEY (FOOD_NO) REFERENCES FOOD  

);

CREATE SEQUENCE SEQ_RID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

COMMIT;


--------------------------------------------------
--------------     RESTAURANT 관련	------------------	
--------------------------------------------------

CREATE TABLE RESTAURANT (
	RESTAURANT_NO	NUMBER PRIMARY KEY,
	RESTAURANT_NAME	VARCHAR2(20)	NOT NULL,
	RESTAURANT_ADDRESS	VARCHAR2(100)	NOT NULL,
	RESTAURANT_PHONE	VARCHAR2(13)	NULL,
	USER_ID	VARCHAR2(30)	NOT NULL,
	STATUS VARCHAR2(1) DEFAULT 'Y'        -- 새로 추가 삭제여부 확인
);


CREATE SEQUENCE SEQ_RID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

COMMIT;


--------------------------------------------------
--------------     FOOD 관련	------------------	
--------------------------------------------------


CREATE TABLE FOOD (
	FOOD_NO	NUMBER PRIMARY KEY,
	FOOD_NAME	VARCHAR2(10)	NOT NULL,
	FOOD_KIND	VARCHAR2(10)	NOT NULL,
	FOOD_TYPE	VARCHAR2(10)	NOT NULL,
	RESTAURANT_NO	NUMBER	NOT NULL,
	STATUS	VARCHAR2(1)	NOT NULL	DEFAULT Y, --새로 추가
	FOREIGN KEY (RESTAURANT_NO) REFERENCES BOARD      --외래키 추가 
);

CREATE SEQUENCE SEQ_FID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

COMMIT;


--------------------------------------------------
--------------     BOARD 관련	------------------	
--------------------------------------------------


CREATE TABLE BOARD (
	BOARD_NO NUMBER	PRIMARY KEY,
	BOARD_TYPE NUMBER, -- 새로 추가일반 게시판(1)이냐 사진 게시판(2)이냐 확인필요
	BOARD_TITLE	VARCHAR2(20)	NOT NULL,
	RESTAURANT_NO	NUMBER	NOT NULL,
	FOOD_NO	NUMBER	NOT NULL,
	USER_ID VARCHAR2(30),         	
	BOARD_COUNT	NUMBER	DEFAULT 0,
	BOARD_CONTENT	VARCHAR2(4000)	NOT NULL,
	BOARD_DATE	DATE	NULL,    
  	MODIFY_DATE 	DATE,             --새로 추가
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),   --기존꺼 변경
 	CONSTRAINT FOREIGN KEY (RESTAURANT_NO) REFERENCES RESTAURANT,            --외래키 추가
	FOREIGN KEY (USER_ID) REFERENCES MEMBER,          --외래키로 추가
	FOREIGN KEY (FOOD_NO) REFERENCES FOOD                          --외래키 추가
);

CREATE SEQUENCE SEQ_BID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

COMMIT;

--------------------------------------------------
--------------     IMAGE 관련	------------------	
--------------------------------------------------


CREATE TABLE IMAGE (
	IMAGE_NO NUMBER	 PRIMARY KEY,
	IMAGE_ORIGIN_NAME VARCHAR2(255)	NULL,
	IMAGE_CHANGE_NAME NUMBER	NULL,
	IMAGE_PATH	VARCHAR2(1000)	NULL,
	IMAGE_UPLOAD_DATE	DATE	NOT NULL	DEFAULT SYSDATE,
	IMAGE_LEVEL	NUMBER	NULL,
	STATUS	VARCHAR2(1)	NOT NULL	DEFAULT Y,
	BOARD_NO	NUMBER	NOT NULL,
	FOREIGN KEY (BOARD_NO) REFERENCES BOARD      --외래키 추가 
);

CREATE SEQUENCE SEQ_IID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

COMMIT;


ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMEBER PRIMARY KEY (
	USER_ID
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NOTICE_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	COMMENT_NO
);

ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (
	RESTAURANT_NO
);

ALTER TABLE IMAGE ADD CONSTRAINT PK_IMAGE PRIMARY KEY (
	IMAGE_NO
);

ALTER TABLE FOOD ADD CONSTRAINT PK_FOOD PRIMARY KEY (
	FOOD_NO
);


--------------------------------------------------
--------------------- commit ---------------------
--------------------------------------------------

COMMIT;


