/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-25 06:55:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.MZBoard;
import java.util.ArrayList;

public final class foods_005freview_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("board.model.vo.MZBoard");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
 
	MZBoard b = (MZBoard)request.getAttribute("board"); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>맛조 - 상세페이지</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <link href=\"css/foods_styling.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- style sheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/foods_detail.css\" >\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  @media (min-width: 768px){\r\n");
      out.write("    .cardContainer > div {\r\n");
      out.write("      flex-basis: 49%;\r\n");
      out.write("    }\r\n");
      out.write("  }  \r\n");
      out.write("  @media (min-width: 425px){\r\n");
      out.write("    .cardContainer > div {\r\n");
      out.write("      flex-basis: 99%;\r\n");
      out.write("      /* width: 100%; */\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<header class=\"blog-header py-3\">\r\n");
      out.write("  <div class=\"row flex-nowrap justify-content-between align-items-center\">\r\n");
      out.write("    <div class=\"col-4 pt-1\">\r\n");
      out.write("      <a class=\"link-secondary\" href=\"#\"> </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-4 text-center\">\r\n");
      out.write("      <span class=\"logo_txt\">대한민국 대표 맛집 커뮤니티</span><a class=\"blog-header-logo\" href=\"#\" ><img class=\"logo_img\" src=\"img/MZ logo.png\" alt=\"logo\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-4 d-flex justify-content-end align-items-center\">\r\n");
      out.write("      <a class=\"link-secondary\" href=\"#\" aria-label=\"Search\">\r\n");
      out.write("      </a>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"btn btn-sm btn-outline-secondary signIn\" href=\"#\">Sign in</a>\r\n");
      out.write("      <a class=\"btn btn-sm btn-outline-secondary signUp\" href=\"#\">Sign up</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"bbb nav-scroller py-1 mb-2 \">\r\n");
      out.write("  <nav class=\"nav d-flex justify-content-around\" >\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">한식</a>\r\n");
      out.write("    <a class=\"p-2 nav_cssSelect\" href=\"#\">중식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">양식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">일식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">디저트</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">공지사항</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- main -->\r\n");
      out.write("<main class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("<div class=\"p-4 p-md-5 mb-4 text-white bg-dark\">\r\n");
      out.write("\r\n");
      out.write("  이미지 추가\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- main content -->\r\n");
      out.write("<!-- articleNeck_text  articleNeck_thumbnail -->\r\n");
      out.write("<div class=\"article\">\r\n");
      out.write("  <div class=\"articleHead\">\r\n");
      out.write("    <h4 class=\"card-title mb-5 text-center\">중화요리 팔공</h4>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"articleSubTitle\" >\r\n");
      out.write("    <div class=\"articleMainTop\">\r\n");
      out.write("      <strong class=\"mt-5 reviewCategory\">중식 </strong>\r\n");
      out.write("      <div class=\"reviewDateTie\">\r\n");
      out.write("        <span class=\"reviewDate justify-content-center\" style=\"width:5%\">22.02.22</span>\r\n");
      out.write("        <span class=\"reviewDate\">조회수 48회 </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <p class=\"\">위치 : 서울 관악구 신림동 10-621 지하 1층 </p>\r\n");
      out.write("      <p class=\"\">Tel : 02-877-9815</p>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <span class=\"reviewFeatureTitle\">간단 소개 </span>\r\n");
      out.write("        <p class=\"\"> 줄서서 먹는 오랜 맛집. 짬뽕의 해물 양이 많고 푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"img\">\r\n");
      out.write("      <!-- image table : image.image_NO -->\r\n");
      out.write("      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/review01 palgong.png\" class=\"img-fluid img_cut\"  alt=\"중화요리 팔공 리뷰\">\r\n");
      out.write("    </div>  \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- 캐러셀 -->\r\n");
      out.write("  <div id=\"carouselExampleIndicators\" class=\"carousel slide \" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-indicators\">\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-inner mb-5\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/review01 palgong.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/review01-1 palgong.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/review01-2 palgong.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 캐러셀 버튼 -->\r\n");
      out.write("      <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("        <div class=\"btnBox\"><span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span></div>\r\n");
      out.write("        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("        <div class=\"btnBox\"><span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span></div>\r\n");
      out.write("        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("      </button>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <div class=\"articleMainBotton mb-5\">\r\n");
      out.write("    <p>\r\n");
      out.write("    <span class=\"\"> 음식 카테고리 : 중식</span><br>\r\n");
      out.write("	동네에 있어 감사한 중식당<br>\r\n");
      out.write("지난번에 볶음밥을 맛있게 먹었던 팔공에 다시 방문했다. 지난 방문 때는 대기 없이 먹을 수 있었는데 이번에는 30분 정도 대기해야 했다.<br> \r\n");
      out.write("대기 후에 테이블에 앉아 해물짬뽕과 군만두를 주문했다. 군만두가 먼저 나온 뒤 뒤이어 바로 짬뽕이 나왔다.<br><br> \r\n");
      out.write("군만두 : 갈색 빛깔로 잘 튀겨진 군만두는 피와 소 모두 특별하진 않았지만 바로 튀겨줬기 때문에 맛있게 먹었다. <br>\r\n");
      out.write("해물짬뽕 : 진한 국물과 함께 조개, 오징어, 새우, 표고, 피망, 브로콜리 등 다양한 재료들이 볶아져 나왔다. <br> \r\n");
      out.write("닭육수와 해산물의 감칠맛과 야채들의 달콤함에 불맛까지 더해져 깊으면서도 너무 기름지지 않고 깔끔한 국물이 좋았다. 해산물들도 잘 익혀 부드럽고 쫄깃하게 먹을 수 있었다.<br> \r\n");
      out.write("손님들이 몰리는 식사시간에도 한 그릇, 한 그릇 바로 바로 조리하는 정성이 고맙다. 동네에 이렇게 정성스럽고 맛있는 중식당이 있어 기쁘고 감사하다.<br>\r\n");
      out.write("      </p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 글쓰기 버튼 -->\r\n");
      out.write("<div class=\"btn-toolbar mb-5\" role=\"toolbar\" aria-label=\"Toolbar with button groups\"\r\n");
      out.write("      style=\"float: right;\">\r\n");
      out.write("  <div class=\"btn-group me-1 \" role=\"group\" aria-label=\"First group\">\r\n");
      out.write("    <button type=\"button\" class=\"btn Writing\" \r\n");
      out.write("            data-bs-toggle=\"button\" autocomplete=\"off\">목록</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"btn-group me-5\" role=\"group\" aria-label=\"Second group\">\r\n");
      out.write("    <button type=\"button\" class=\"btn Writing\"\r\n");
      out.write("            data-bs-toggle=\"button\" autocomplete=\"off\"\r\n");
      out.write("            onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardWriting.bo'\"\r\n");
      out.write("            >글쓰기</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>    \r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
