/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-23 11:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class foods_005freview_005fKorean2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>맛조</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <link href=\"css/foods_styling.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/foods_styling5.css\" >\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  @media (min-width: 768px){\r\n");
      out.write("    .cardContainer > div {\r\n");
      out.write("      flex-basis: 49%;\r\n");
      out.write("    }\r\n");
      out.write("  }  \r\n");
      out.write("  @media (min-width: 425px){\r\n");
      out.write("    .cardContainer > div {\r\n");
      out.write("      flex-basis: 99%;\r\n");
      out.write("      /* width: 100%; */\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<header class=\"blog-header py-3\">\r\n");
      out.write("  <div class=\"row flex-nowrap justify-content-between align-items-center\">\r\n");
      out.write("    <div class=\"col-4 pt-1\">\r\n");
      out.write("      <a class=\"link-secondary\" href=\"#\"> </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-4 text-center\">\r\n");
      out.write("      <span class=\"logo_txt\">대한민국 대표 맛집 커뮤니티</span><a class=\"blog-header-logo\" href=\"#\" ><img class=\"logo_img\" src=\"img/teamLogo.png\" alt=\"logo\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-4 d-flex justify-content-end align-items-center\">\r\n");
      out.write("      <a class=\"link-secondary\" href=\"#\" aria-label=\"Search\">\r\n");
      out.write("      </a>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"btn btn-sm btn-outline-secondary signIn\" href=\"#\">Sign in</a>\r\n");
      out.write("      <a class=\"btn btn-sm btn-outline-secondary signUp\" href=\"#\">Sign up</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"bbb nav-scroller py-1 mb-2 \">\r\n");
      out.write("  <nav class=\"nav d-flex justify-content-between\" >\r\n");
      out.write("    <a class=\"p-2 nav_cssSelect\" href=\"#\">한식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">중식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">양식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">일식</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">디저트</a>\r\n");
      out.write("    <a class=\"p-2 nav_css\" href=\"#\">공지사항</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("<div class=\"p-4 p-md-5 mb-4 text-white bg-dark\">\r\n");
      out.write("\r\n");
      out.write("  이미지 추가\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"cardContainer\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"cardBox\" id=\"cardBoxDetail\">\r\n");
      out.write("    <div class=\"\">\r\n");
      out.write("      <img src=\"0_MZ/WebContent/images/logo.png\" class=\"img-fluid img_cut\"  alt=\"중화요리 팔공 리뷰\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cardBoxText\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <strong class=\"mb-lg-1 reviewCategory\">중식</strong>\r\n");
      out.write("        <h5 class=\"card-title cardTitle\">중화요리 팔공1</h5>\r\n");
      out.write("        <p class=\"card-text mb-1 reviewDate\">22.02.22 | 조회수 50회</p>\r\n");
      out.write("        <p class=\"card-text mb-auto reviewNormal\">위치 : 서울 관악구 신림동 10-621 지하 1층</p>\r\n");
      out.write("        <p class=\"card-text mt-3 mb-auto reviewFeatureTitle\">간단 소개</p>\r\n");
      out.write("        <p class=\"card-text reviewNormal\">푸짐한 양과 아낌없는 재료\r\n");
      out.write("          푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cardBox\" id=\"cardBoxDetail\">\r\n");
      out.write("      <div class=\"cardImg\">\r\n");
      out.write("        <img src=\"0_MZ/WebContent/images/logo.png\" class=\"img-fluid  img_cut\" alt=\"중화요리 팔공 리뷰\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"cardTxt\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <strong class=\"mb-lg-1 reviewCategory\">중식</strong>\r\n");
      out.write("          <h5 class=\"card-title cardTitle\">짜장면집2</h5>\r\n");
      out.write("          <p class=\"card-text mb-1 reviewDate\">20.02.10 | 조회수 50회</p>\r\n");
      out.write("          <p class=\"card-text mb-auto reviewNormal\">위치 : 서울 관악구 신원로 16 1층</p>\r\n");
      out.write("          <p class=\"card-text mt-3 mb-auto reviewFeatureTitle\">간단 소개</p>\r\n");
      out.write("          <p class=\"card-text reviewNormal\">이보다 쌀 수 있을까? 극한의 가성비</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cardBox\" id=\"cardBoxDetail\">\r\n");
      out.write("    <div class=\"\">\r\n");
      out.write("      <img src=\"0_MZ/WebContent/images/logo.png\" class=\"img-fluid img_cut\"  alt=\"중화요리 팔공 리뷰\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cardBoxText\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <strong class=\"mb-lg-1 reviewCategory\">중식</strong>\r\n");
      out.write("        <h5 class=\"card-title cardTitle\">중화요리 팔공3</h5>\r\n");
      out.write("        <p class=\"card-text mb-1 reviewDate\">22.02.22 | 조회수 50회</p>\r\n");
      out.write("        <p class=\"card-text mb-auto reviewNormal\">위치 : 서울 관악구 신림동 10-621 지하 1층</p>\r\n");
      out.write("        <p class=\"card-text mt-3 mb-auto reviewFeatureTitle\">간단 소개</p>\r\n");
      out.write("        <p class=\"card-text reviewNormal\">푸짐한 양과 아낌없는 재료\r\n");
      out.write("          푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료푸짐한 양과 아낌없는 재료\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cardBox\" id=\"cardBoxDetail\">\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <img src=\"0_MZ/WebContent/images/logo.png\" class=\"img-fluid img_cut\" alt=\"중화요리 팔공 리뷰\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <strong class=\"mb-lg-1 reviewCategory\">중식</strong>\r\n");
      out.write("          <h5 class=\"card-title cardTitle\">짜장면집4</h5>\r\n");
      out.write("          <p class=\"card-text mb-1 reviewDate\">20.02.10 | 조회수 50회</p>\r\n");
      out.write("          <p class=\"card-text mb-auto reviewNormal\">위치 : 서울 관악구 신원로 16 1층</p>\r\n");
      out.write("          <p class=\"card-text mt-3 mb-auto reviewFeatureTitle\">간단 소개</p>\r\n");
      out.write("          <p class=\"card-text reviewNormal\">이보다 쌀 수 있을까? 극한의 가성비</p>\r\n");
      out.write("          <!-- <p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p> -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav aria-label=\"Page navigation example\">\r\n");
      out.write("  <ul class=\"pagination justify-content-center pagination-lg\">\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button type=\"button\" class=\"btn btn-sm Writing\" style=\"float: right;\"\r\n");
      out.write("        data-bs-toggle=\"button\" autocomplete=\"off\"\r\n");
      out.write("        onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardWriting.bo'\"\r\n");
      out.write("        >글쓰기\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $(function(){\r\n");
      out.write("    $('#cardBoxDetail *').mouseenter(function(){\r\n");
      out.write("      $(this).parent().css({'border':'2px solid #F08000','cursor':'pointer'});\r\n");
      out.write("    }).mouseout(function(){\r\n");
      out.write("      $(this).parent().css('border','none'); \r\n");
      out.write("    }).click(function(){ // 이 게시글만 보겠다고 select해올거면 조건을 넣어줘야하는데 뭐로 나뉠 수 있을까? 글번호 . pk라서 겹칠 일이 없음.\r\n");
      out.write("      var num = $(this).parent().children().eq(0).text(); \r\n");
      out.write("      location.href = '");
      out.print( request.getContextPath() );
      out.write("/detail.bo?no=' + num; \r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
